In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('../../csvs/estaticos_portfolio1.csv')
df.head()

,Unnamed: 0,id,fl_matriz,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,setor,idade_empresa_anos,idade_emp_cat,...,media_meses_servicos,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais
0,0,dabe79bec87c88ae04e869bf6bd321ee5e1893cecf6625...,True,EMPRESARIO INDIVIDUAL,PI,OUTROS,COMERCIO VAREJISTA,COMERCIO,0.646575,<= 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,32e5f4e10932153a7ba869cb0386e7e02d49d2461046b8...,False,EMPRESARIO INDIVIDUAL,MA,OUTROS,COMERCIO VAREJISTA,COMERCIO,6.586301,5 a 10,...,NaN,NaN,NaN,0.0,0.0,2.0,NaN,-100.0,0.0,4
2,2,a95d6f30bba445bd3d6b0c5b36f865b38ec01d17336090...,True,EMPRESARIO INDIVIDUAL,MA,OUTROS,COMERCIO VAREJISTA,COMERCIO,8.010959,5 a 10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,3,6cb309685cea0b6d2988818792ec2e6fcb2bd02e0afa9e...,True,EMPRESARIO INDIVIDUAL,RN,OUTROS,COMERCIO VAREJISTA,COMERCIO,20.863014,> 20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,f72aa7fa6787b0a5a1c88885b6120850df8ee0f71adc25...,True,SOCIEDADE EMPRESARIA LIMITADA,RN,ENTIDADES EMPRESARIAIS,COMERCIO VAREJISTA,COMERCIO,18.726027,15 a 20,...,39.454762,91.2,19.333333,14.0,15.0,25.0,-6.666667,-44.0,0.0,3

In [4]:
df.describe()

,Unnamed: 0,idade_empresa_anos,vl_total_tancagem,vl_total_veiculos_antt,vl_total_veiculos_leves,vl_total_veiculos_pesados,qt_art,vl_total_veiculos_pesados_grupo,vl_total_veiculos_leves_grupo,vl_total_tancagem_grupo,...,media_meses_servicos,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais
count,555.000000,555.000000,0.0,0.0,38.000000,38.000000,4.000000,555.000000,555.000000,0.0,...,101.000000,101.000000,101.000000,131.000000,131.000000,131.000000,97.000000,91.000000,131.000000,555.000000
mean,277.000000,10.139247,NaN,NaN,1.473684,0.526316,3.250000,0.861261,0.542342,NaN,...,49.929006,72.989769,33.615512,4.458015,4.679389,4.908397,-0.132325,-2.073969,9.557799,1.236036
std,160.358972,9.641625,NaN,NaN,1.309773,1.330248,3.201562,16.312180,8.502044,NaN,...,40.968949,61.443495,37.410508,9.053057,9.875585,9.396767,40.324314,124.955846,28.315487,16.288026
min,0.000000,0.052055,NaN,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,NaN,...,5.406667,5.800000,2.166667,0.000000,0.000000,0.000000,-100.000000,-100.000000,0.000000,0.000000
25%,138.500000,2.924658,NaN,NaN,1.000000,0.000000,1.750000,0.000000,0.000000,NaN,...,22.323077,25.233333,5.966667,1.000000,0.000000,0.000000,0.000000,-45.076923,0.000000,0.000000
50%,277.000000,6.709589,NaN,NaN,1.000000,0.000000,2.000000,0.000000,0.000000,NaN,...,41.966667,54.700000,22.133333,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000
75%,415.500000,15.494521,NaN,NaN,2.000000,0.750000,3.500000,0.000000,0.000000,NaN,...,65.916667,93.266667,48.566667,4.000000,4.500000,5.000000,0.000000,0.000000,0.000000,0.000000
max,554.000000,47.517808,NaN,NaN,6.000000,7.000000,8.000000,382.000000,199.000000,NaN,...,228.155556,309.333333,192.633333,70.000000,75.000000,74.000000,200.000000,800.000000,213.333333,374.000000

In [5]:
df.columns

Index(['Unnamed: 0', 'id', 'fl_matriz', 'de_natureza_juridica', 'sg_uf',
       'natureza_juridica_macro', 'de_ramo', 'setor', 'idade_empresa_anos',
       'idade_emp_cat',
       ...
       'media_meses_servicos', 'max_meses_servicos', 'min_meses_servicos',
       'qt_funcionarios', 'qt_funcionarios_12meses', 'qt_funcionarios_24meses',
       'tx_crescimento_12meses', 'tx_crescimento_24meses', 'tx_rotatividade',
       'qt_filiais'],
      dtype='object', length=182)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Columns: 182 entries, Unnamed: 0 to qt_filiais
dtypes: bool(14), float64(142), int64(4), object(22)
memory usage: 736.2+ KB

# Problema - Quais sÃ£o os clientes potenciais das empresas 1, 2 e 3

-

# AnÃ¡lise ExploratÃ³ria

In [11]:
aux = pd.DataFrame({'variables': df.columns,
                    'tipos': df.dtypes,
                    'percentual_faltante': df.isna().sum() / df.shape[0]})

In [23]:
new_aux = aux[aux['percentual_faltante']]
# new_aux['tipos'].value_counts()
new_aux
# variables_with_high_missing_data = [ {"variable_name": , "missing_percentage": } for item in ]

,variables,tipos,percentual_faltante
vl_total_tancagem,vl_total_tancagem,float64,1.000000
vl_total_veiculos_antt,vl_total_veiculos_antt,float64,1.000000
vl_total_veiculos_leves,vl_total_veiculos_leves,float64,0.931532
vl_total_veiculos_pesados,vl_total_veiculos_pesados,float64,0.931532
qt_art,qt_art,float64,0.992793
...,...,...,...
qt_funcionarios_12meses,qt_funcionarios_12meses,float64,0.763964
qt_funcionarios_24meses,qt_funcionarios_24meses,float64,0.763964
tx_crescimento_12meses,tx_crescimento_12meses,float64,0.825225
tx_crescimento_24meses,tx_crescimento_24meses,float64,0.836036
tx_rotatividade,tx_rotatividade,float64,0.763964

In [5]:
columns = df.columns
def val_counts():
    for column in columns:
        print(f'-------> Coluna: {column}')
        print(df[column].value_counts())
        obj = {
            "total": len(df[column]),
            "percentages": (df[column].value_counts()/df[column].count())*100
        }
        print(obj)
    
val_counts()

-------> Coluna: Unnamed: 0
554    1
182    1
188    1
187    1
186    1
      ..
375    1
376    1
377    1
378    1
0      1
Name: Unnamed: 0, Length: 555, dtype: int64
{'total': 555, 'percentages': 554    0.18018
182    0.18018
188    0.18018
187    0.18018
186    0.18018
        ...
375    0.18018
376    0.18018
377    0.18018
378    0.18018
0      0.18018
Name: Unnamed: 0, Length: 555, dtype: float64}
-------> Coluna: id
6b1dc848c66193d9ad142db3cd2752f94addc6efba9e871603e92a792ef6863f    1
91b91930558993600d66666c48403b3f424707f808a85f13d00955824f2a5548    1
334606a197541d23118018ca9f49271f6795aee4f3e9667163947b862cb659b0    1
285adb974703640fe60532fb1bbf4ada385f675a65c00629aae21c75fafdef17    1
ec4fcd0439535809488cfda9446eeda8079128d755246091f03cc2b11f591abd    1
                                                                   ..
9714f7f05a541c0d0d14853b6468a78f3adffe2fdcc8c58046c29ebdbee300fd    1
1b4ae7ec9748fdd5d11f8ce47e04028a3788d5967ec7d66b94ca5086ac6d6ec9    1
5a31c4585c1dd54c48963202b7493c9a681f8401575f3f7c1b83c6dfb6eb667f    1
d813d990bfe3682e430fa1b09b38bf772861fb6f85428e2ec790e5c0131f8414    1
d02ca50913607dd2f6e3c514a42cb69179b3f0d9631f73ea3ac7dc071128f5ee    1
Name: id, Length: 555, dtype: int64
{'total': 555, 'percentages': 6b1dc848c66193d9ad142db3cd2752f94addc6efba9e871603e92a792ef6863f    0.18018
91b91930558993600d66666c48403b3f424707f808a85f13d00955824f2a5548    0.18018
334606a197541d23118018ca9f49271f6795aee4f3e9667163947b862cb659b0    0.18018
285adb974703640fe60532fb1bbf4ada385f675a65c00629aae21c75fafdef17    0.18018
ec4fcd0439535809488cfda9446eeda8079128d755246091f03cc2b11f591abd    0.18018
                                                                     ...
9714f7f05a541c0d0d14853b6468a78f3adffe2fdcc8c58046c29ebdbee300fd    0.18018
1b4ae7ec9748fdd5d11f8ce47e04028a3788d5967ec7d66b94ca5086ac6d6ec9    0.18018
5a31c4585c1dd54c48963202b7493c9a681f8401575f3f7c1b83c6dfb6eb667f    0.18018
d813d990bfe3682e430fa1b09b38bf772861fb6f85428e2ec790e5c0131f8414    0.18018
d02ca50913607dd2f6e3c514a42cb69179b3f0d9631f73ea3ac7dc071128f5ee    0.18018
Name: id, Length: 555, dtype: float64}
-------> Coluna: fl_matriz
True     519
False     36
Name: fl_matriz, dtype: int64
{'total': 555, 'percentages': True     93.513514
False     6.486486
Name: fl_matriz, dtype: float64}
-------> Coluna: de_natureza_juridica
EMPRESARIO INDIVIDUAL                                                     432
SOCIEDADE EMPRESARIA LIMITADA                                             105
EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITADA DE NATUREZA EMPRESARIA     15
SOCIEDADE EMPRESARIA EM NOME COLETIVO                                       1
SOCIEDADE EM CONTA DE PARTICIPACAO                                          1
SOCIEDADE ANONIMA FECHADA                                                   1
Name: de_natureza_juridica, dtype: int64
{'total': 555, 'percentages': EMPRESARIO INDIVIDUAL                                                     77.837838
SOCIEDADE EMPRESARIA LIMITADA                                             18.918919
EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITADA DE NATUREZA EMPRESARIA     2.702703
SOCIEDADE EMPRESARIA EM NOME COLETIVO                                      0.180180
SOCIEDADE EM CONTA DE PARTICIPACAO                                         0.180180
SOCIEDADE ANONIMA FECHADA                                                  0.180180
Name: de_natureza_juridica, dtype: float64}
-------> Coluna: sg_uf
MA    157
RN    116
PI    103
AM     94
RO     64
AC     21
Name: sg_uf, dtype: int64
{'total': 555, 'percentages': MA    28.288288
RN    20.900901
PI    18.558559
AM    16.936937
RO    11.531532
AC     3.783784
Name: sg_uf, dtype: float64}
-------> Coluna: natureza_juridica_macro
OUTROS                    447
ENTIDADES EMPRESARIAIS    108
Name: natureza_juridica_macro, dtype: int64
{'total': 555, 'percentages': OUTROS                    80.540541
ENTIDADES EMPRESARIAIS    19.459459
Name: natureza_juridica_macro, dtype: float64}
-------> Coluna: de_ramo
COMERCIO VAREJISTA    496
BENS DE CONSUMO        59
Name: de_ramo, dtype: int64
{'total': 555, 'percentages': COMERCIO VAREJISTA    89.369369
BENS DE CONSUMO       10.630631
Name: de_ramo, dtype: float64}
-------> Coluna: setor
COMERCIO     496
INDUSTRIA     52
SERVIÃ‡O        7
Name: setor, dtype: int64
{'total': 555, 'percentages': COMERCIO     89.369369
INDUSTRIA     9.369369
SERVIÃ‡O       1.261261
Name: setor, dtype: float64}
-------> Coluna: idade_empresa_anos
8.010959     4
1.682192     3
1.583562     3
9.750685     2
1.158904     2
            ..
31.060274    1
2.153425     1
11.613699    1
1.808219     1
5.000000     1
Name: idade_empresa_anos, Length: 522, dtype: int64
{'total': 555, 'percentages': 8.010959     0.720721
1.682192     0.540541
1.583562     0.540541
9.750685     0.360360
1.158904     0.360360
               ...
31.060274    0.180180
2.153425     0.180180
11.613699    0.180180
1.808219     0.180180
5.000000     0.180180
Name: idade_empresa_anos, Length: 522, dtype: float64}
-------> Coluna: idade_emp_cat
1 a 5      157
5 a 10     144
> 20        92
<= 1        56
10 a 15     55
15 a 20     51
Name: idade_emp_cat, dtype: int64
{'total': 555, 'percentages': 1 a 5      28.288288
5 a 10     25.945946
> 20       16.576577
<= 1       10.090090
10 a 15     9.909910
15 a 20     9.189189
Name: idade_emp_cat, dtype: float64}
-------> Coluna: fl_me
False    553
True       2
Name: fl_me, dtype: int64
{'total': 555, 'percentages': False    99.63964
True      0.36036
Name: fl_me, dtype: float64}
-------> Coluna: fl_sa
False    546
True       9
Name: fl_sa, dtype: int64
{'total': 555, 'percentages': False    98.378378
True      1.621622
Name: fl_sa, dtype: float64}
-------> Coluna: fl_epp
False    555
Name: fl_epp, dtype: int64
{'total': 555, 'percentages': False    100.0
Name: fl_epp, dtype: float64}
-------> Coluna: fl_mei
False    337
True     218
Name: fl_mei, dtype: int64
{'total': 555, 'percentages': False    60.720721
True     39.279279
Name: fl_mei, dtype: float64}
-------> Coluna: fl_ltda
False    555
Name: fl_ltda, dtype: int64
{'total': 555, 'percentages': False    100.0
Name: fl_ltda, dtype: float64}
-------> Coluna: dt_situacao
2005-11-03    100
2010-10-26      4
2017-03-29      3
2006-12-02      3
2017-02-21      3
             ...
2015-04-28      1
2007-05-15      1
2012-05-29      1
2012-06-04      1
2017-06-15      1
Name: dt_situacao, Length: 416, dtype: int64
{'total': 555, 'percentages': 2005-11-03    18.018018
2010-10-26     0.720721
2017-03-29     0.540541
2006-12-02     0.540541
2017-02-21     0.540541
                ...
2015-04-28     0.180180
2007-05-15     0.180180
2012-05-29     0.180180
2012-06-04     0.180180
2017-06-15     0.180180
Name: dt_situacao, Length: 416, dtype: float64}
-------> Coluna: fl_st_especial
False    555
Name: fl_st_especial, dtype: int64
{'total': 555, 'percentages': False    100.0
Name: fl_st_especial, dtype: float64}
-------> Coluna: fl_email
False    300
True     255
Name: fl_email, dtype: int64
{'total': 555, 'percentages': False    54.054054
True     45.945946
Name: fl_email, dtype: float64}
-------> Coluna: fl_telefone
True     400
False    155
Name: fl_telefone, dtype: int64
{'total': 555, 'percentages': True     72.072072
False    27.927928
Name: fl_telefone, dtype: float64}
-------> Coluna: fl_rm
NAO    311
SIM    244
Name: fl_rm, dtype: int64
{'total': 555, 'percentages': NAO    56.036036
SIM    43.963964
Name: fl_rm, dtype: float64}
-------> Coluna: nm_divisao
COMERCIO VAREJISTA                                              496
FABRICACAO DE PRODUTOS ALIMENTICIOS                              16
FABRICACAO DE PRODUTOS DE MADEIRA                                 9
FABRICACAO DE MOVEIS                                              9
CONFECCAO DE ARTIGOS DO VESTUARIO E ACESSORIOS                    9
FABRICACAO DE PRODUTOS DIVERSOS                                   8
MANUTENCAO REPARACAO E INSTALACAO DE MAQUINAS E EQUIPAMENTOS      7
FABRICACAO DE BEBIDAS                                             1
Name: nm_divisao, dtype: int64
{'total': 555, 'percentages': COMERCIO VAREJISTA                                              89.369369
FABRICACAO DE PRODUTOS ALIMENTICIOS                              2.882883
FABRICACAO DE PRODUTOS DE MADEIRA                                1.621622
FABRICACAO DE MOVEIS                                             1.621622
CONFECCAO DE ARTIGOS DO VESTUARIO E ACESSORIOS                   1.621622
FABRICACAO DE PRODUTOS DIVERSOS                                  1.441441
MANUTENCAO REPARACAO E INSTALACAO DE MAQUINAS E EQUIPAMENTOS     1.261261
FABRICACAO DE BEBIDAS                                            0.180180
Name: nm_divisao, dtype: float64}
-------> Coluna: nm_segmento
COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E MOTOCICLETAS    496
INDUSTRIAS DE TRANSFORMACAO                                    59
Name: nm_segmento, dtype: int64
{'total': 555, 'percentages': COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E MOTOCICLETAS    89.369369
INDUSTRIAS DE TRANSFORMACAO                                   10.630631
Name: nm_segmento, dtype: float64}
-------> Coluna: fl_spa
False    555
Name: fl_spa, dtype: int64
{'total': 555, 'percentages': False    100.0
Name: fl_spa, dtype: float64}
-------> Coluna: fl_antt
False    551
True       4
Name: fl_antt, dtype: int64
{'total': 555, 'percentages': False    99.279279
True      0.720721
Name: fl_antt, dtype: float64}
-------> Coluna: fl_veiculo
False    517
True      38
Name: fl_veiculo, dtype: int64
{'total': 555, 'percentages': False    93.153153
True      6.846847
Name: fl_veiculo, dtype: float64}
-------> Coluna: vl_total_tancagem
Series([], Name: vl_total_tancagem, dtype: int64)
{'total': 555, 'percentages': Series([], Name: vl_total_tancagem, dtype: float64)}
-------> Coluna: vl_total_veiculos_antt
Series([], Name: vl_total_veiculos_antt, dtype: int64)
{'total': 555, 'percentages': Series([], Name: vl_total_veiculos_antt, dtype: float64)}
-------> Coluna: vl_total_veiculos_leves
1.0    23
2.0     6
0.0     4
3.0     3
6.0     2
Name: vl_total_veiculos_leves, dtype: int64
{'total': 555, 'percentages': 1.0    60.526316
2.0    15.789474
0.0    10.526316
3.0     7.894737
6.0     5.263158
Name: vl_total_veiculos_leves, dtype: float64}
-------> Coluna: vl_total_veiculos_pesados
0.0    28
1.0     7
7.0     1
4.0     1
2.0     1
Name: vl_total_veiculos_pesados, dtype: int64
{'total': 555, 'percentages': 0.0    73.684211
1.0    18.421053
7.0     2.631579
4.0     2.631579
2.0     2.631579
Name: vl_total_veiculos_pesados, dtype: float64}
-------> Coluna: fl_optante_simples
True     286
False    168
Name: fl_optante_simples, dtype: int64
{'total': 555, 'percentages': True     62.995595
False    37.004405
Name: fl_optante_simples, dtype: float64}
-------> Coluna: qt_art
2.0    2
8.0    1
1.0    1
Name: qt_art, dtype: int64
{'total': 555, 'percentages': 2.0    50.0
8.0    25.0
1.0    25.0
Name: qt_art, dtype: float64}
-------> Coluna: vl_total_veiculos_pesados_grupo
0      535
1        9
8        2
7        2
4        2
2        2
382      1
40       1
5        1
Name: vl_total_veiculos_pesados_grupo, dtype: int64
{'total': 555, 'percentages': 0      96.396396
1       1.621622
8       0.360360
7       0.360360
4       0.360360
2       0.360360
382     0.180180
40      0.180180
5       0.180180
Name: vl_total_veiculos_pesados_grupo, dtype: float64}
-------> Coluna: vl_total_veiculos_leves_grupo
0      513
1       23
3        7
2        5
6        2
199      1
17       1
10       1
5        1
4        1
Name: vl_total_veiculos_leves_grupo, dtype: int64
{'total': 555, 'percentages': 0      92.432432
1       4.144144
3       1.261261
2       0.900901
6       0.360360
199     0.180180
17      0.180180
10      0.180180
5       0.180180
4       0.180180
Name: vl_total_veiculos_leves_grupo, dtype: float64}
-------> Coluna: vl_total_tancagem_grupo
Series([], Name: vl_total_tancagem_grupo, dtype: int64)
{'total': 555, 'percentages': Series([], Name: vl_total_tancagem_grupo, dtype: float64)}
-------> Coluna: vl_total_veiculos_antt_grupo
Series([], Name: vl_total_veiculos_antt_grupo, dtype: int64)
{'total': 555, 'percentages': Series([], Name: vl_total_veiculos_antt_grupo, dtype: float64)}
-------> Coluna: vl_potenc_cons_oleo_gas
14.0    1
2.0     1
8.0     1
Name: vl_potenc_cons_oleo_gas, dtype: int64
{'total': 555, 'percentages': 14.0    33.333333
2.0     33.333333
8.0     33.333333
Name: vl_potenc_cons_oleo_gas, dtype: float64}
-------> Coluna: fl_optante_simei
False    316
True     138
Name: fl_optante_simei, dtype: int64
{'total': 555, 'percentages': False    69.603524
True     30.396476
Name: fl_optante_simei, dtype: float64}
-------> Coluna: sg_uf_matriz
MA    156
RN    116
PI    103
AM     93
RO     64
AC     22
CE      1
Name: sg_uf_matriz, dtype: int64
{'total': 555, 'percentages': MA    28.108108
RN    20.900901
PI    18.558559
AM    16.756757
RO    11.531532
AC     3.963964
CE     0.180180
Name: sg_uf_matriz, dtype: float64}
-------> Coluna: de_saude_tributaria
VERDE       167
AZUL        128
AMARELO     113
CINZA        86
LARANJA      47
VERMELHO      3
Name: de_saude_tributaria, dtype: int64
{'total': 555, 'percentages': VERDE       30.698529
AZUL        23.529412
AMARELO     20.772059
CINZA       15.808824
LARANJA      8.639706
VERMELHO     0.551471
Name: de_saude_tributaria, dtype: float64}
-------> Coluna: de_saude_rescencia
ACIMA DE 1 ANO    453
ATE 1 ANO          55
SEM INFORMACAO     36
Name: de_saude_rescencia, dtype: int64
{'total': 555, 'percentages': ACIMA DE 1 ANO    83.272059
ATE 1 ANO         10.110294
SEM INFORMACAO     6.617647
Name: de_saude_rescencia, dtype: float64}
-------> Coluna: nu_meses_rescencia
23.0    124
22.0    107
24.0     51
48.0     35
25.0     35
26.0     28
21.0     22
27.0     16
9.0      13
10.0     13
50.0     11
8.0      11
7.0      10
47.0      6
11.0      5
19.0      5
49.0      4
28.0      3
54.0      3
12.0      3
52.0      1
40.0      1
20.0      1
Name: nu_meses_rescencia, dtype: int64
{'total': 555, 'percentages': 23.0    24.409449
22.0    21.062992
24.0    10.039370
48.0     6.889764
25.0     6.889764
26.0     5.511811
21.0     4.330709
27.0     3.149606
9.0      2.559055
10.0     2.559055
50.0     2.165354
8.0      2.165354
7.0      1.968504
47.0     1.181102
11.0     0.984252
19.0     0.984252
49.0     0.787402
28.0     0.590551
54.0     0.590551
12.0     0.590551
52.0     0.196850
40.0     0.196850
20.0     0.196850
Name: nu_meses_rescencia, dtype: float64}
-------> Coluna: de_nivel_atividade
MEDIA          280
ALTA           153
BAIXA          116
MUITO BAIXA      2
Name: de_nivel_atividade, dtype: int64
{'total': 555, 'percentages': MEDIA          50.816697
ALTA           27.767695
BAIXA          21.052632
MUITO BAIXA     0.362976
Name: de_nivel_atividade, dtype: float64}
-------> Coluna: de_indicador_telefone
BOA    54
Name: de_indicador_telefone, dtype: int64
{'total': 555, 'percentages': BOA    100.0
Name: de_indicador_telefone, dtype: float64}
-------> Coluna: fl_simples_irregular
False    555
Name: fl_simples_irregular, dtype: int64
{'total': 555, 'percentages': False    100.0
Name: fl_simples_irregular, dtype: float64}
-------> Coluna: vl_frota
34236.0     1
27023.0     1
21094.0     1
49188.0     1
45036.0     1
17861.0     1
22726.0     1
7269.0      1
214064.0    1
20871.0     1
453745.0    1
38332.0     1
52692.0     1
18859.0     1
9542.0      1
159615.0    1
44659.0     1
10392.0     1
68164.0     1
28114.0     1
288551.0    1
47781.0     1
41256.0     1
13385.0     1
125654.0    1
22838.0     1
60847.0     1
3611.0      1
48817.0     1
105957.0    1
182549.0    1
Name: vl_frota, dtype: int64
{'total': 555, 'percentages': 34236.0     3.225806
27023.0     3.225806
21094.0     3.225806
49188.0     3.225806
45036.0     3.225806
17861.0     3.225806
22726.0     3.225806
7269.0      3.225806
214064.0    3.225806
20871.0     3.225806
453745.0    3.225806
38332.0     3.225806
52692.0     3.225806
18859.0     3.225806
9542.0      3.225806
159615.0    3.225806
44659.0     3.225806
10392.0     3.225806
68164.0     3.225806
28114.0     3.225806
288551.0    3.225806
47781.0     3.225806
41256.0     3.225806
13385.0     3.225806
125654.0    3.225806
22838.0     3.225806
60847.0     3.225806
3611.0      3.225806
48817.0     3.225806
105957.0    3.225806
182549.0    3.225806
Name: vl_frota, dtype: float64}
-------> Coluna: empsetorcensitariofaixarendapopulacao
1098.56    2
1316.48    2
2361.38    2
555.90     2
949.29     2
          ..
499.86     1
1062.81    1
846.30     1
464.13     1
1500.00    1
Name: empsetorcensitariofaixarendapopulacao, Length: 391, dtype: int64
{'total': 555, 'percentages': 1098.56    0.493827
1316.48    0.493827
2361.38    0.493827
555.90     0.493827
949.29     0.493827
             ...
499.86     0.246914
1062.81    0.246914
846.30     0.246914
464.13     0.246914
1500.00    0.246914
Name: empsetorcensitariofaixarendapopulacao, Length: 391, dtype: float64}
-------> Coluna: nm_meso_regiao
CENTRO AMAZONENSE         78
LESTE POTIGUAR            77
NORTE MARANHENSE          65
CENTRO NORTE PIAUIENSE    55
OESTE MARANHENSE          36
LESTE MARANHENSE          25
CENTRO MARANHENSE         21
VALE DO ACRE              20
OESTE POTIGUAR            18
SUDESTE PIAUIENSE         17
NORTE PIAUIENSE           16
SUDOESTE PIAUIENSE        15
CENTRAL POTIGUAR          12
SUL MARANHENSE            10
AGRESTE POTIGUAR           9
SUL AMAZONENSE             8
SUDOESTE AMAZONENSE        6
NORTE AMAZONENSE           2
VALE DO JURUA              1
Name: nm_meso_regiao, dtype: int64
{'total': 555, 'percentages': CENTRO AMAZONENSE         15.885947
LESTE POTIGUAR            15.682281
NORTE MARANHENSE          13.238289
CENTRO NORTE PIAUIENSE    11.201629
OESTE MARANHENSE           7.331976
LESTE MARANHENSE           5.091650
CENTRO MARANHENSE          4.276986
VALE DO ACRE               4.073320
OESTE POTIGUAR             3.665988
SUDESTE PIAUIENSE          3.462322
NORTE PIAUIENSE            3.258656
SUDOESTE PIAUIENSE         3.054990
CENTRAL POTIGUAR           2.443992
SUL MARANHENSE             2.036660
AGRESTE POTIGUAR           1.832994
SUL AMAZONENSE             1.629328
SUDOESTE AMAZONENSE        1.221996
NORTE AMAZONENSE           0.407332
VALE DO JURUA              0.203666
Name: nm_meso_regiao, dtype: float64}
-------> Coluna: nm_micro_regiao
MANAUS                            65
NATAL                             58
AGLOMERACAO URBANA DE SAO LUIS    48
TERESINA                          41
IMPERATRIZ                        20
                                  ..
ALTO PARNAIBA PIAUIENSE            1
SERIDO OCIDENTAL                   1
CHAPADAS DAS MANGABEIRAS           1
BOCA DO ACRE                       1
TARAUACA                           1
Name: nm_micro_regiao, Length: 66, dtype: int64
{'total': 555, 'percentages': MANAUS                            13.238289
NATAL                             11.812627
AGLOMERACAO URBANA DE SAO LUIS     9.775967
TERESINA                           8.350305
IMPERATRIZ                         4.073320
                                    ...
ALTO PARNAIBA PIAUIENSE            0.203666
SERIDO OCIDENTAL                   0.203666
CHAPADAS DAS MANGABEIRAS           0.203666
BOCA DO ACRE                       0.203666
TARAUACA                           0.203666
Name: nm_micro_regiao, Length: 66, dtype: float64}
-------> Coluna: fl_passivel_iss
False    442
True     113
Name: fl_passivel_iss, dtype: int64
{'total': 555, 'percentages': False    79.63964
True     20.36036
Name: fl_passivel_iss, dtype: float64}
-------> Coluna: qt_socios
1.0    315
2.0     81
3.0      9
5.0      1
9.0      1
4.0      1
Name: qt_socios, dtype: int64
{'total': 555, 'percentages': 1.0    77.205882
2.0    19.852941
3.0     2.205882
5.0     0.245098
9.0     0.245098
4.0     0.245098
Name: qt_socios, dtype: float64}
-------> Coluna: qt_socios_pf
1.0    317
2.0     80
3.0      8

Name: qt_socios_pj_inaptos, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_socios_pj_inaptos, dtype: float64}
-------> Coluna: vl_idade_media_socios_pj
10.940452    1
18.910335    1
Name: vl_idade_media_socios_pj, dtype: int64
{'total': 555, 'percentages': 10.940452    50.0
18.910335    50.0
Name: vl_idade_media_socios_pj, dtype: float64}
-------> Coluna: vl_idade_maxima_socios_pj
19.334702    1
18.910335    1
Name: vl_idade_maxima_socios_pj, dtype: int64
{'total': 555, 'percentages': 19.334702    50.0
18.910335    50.0
Name: vl_idade_maxima_socios_pj, dtype: float64}
-------> Coluna: vl_idade_minima_socios_pj
2.546201     1
18.910335    1
Name: vl_idade_minima_socios_pj, dtype: int64
{'total': 555, 'percentages': 2.546201     50.0
18.910335    50.0
Name: vl_idade_minima_socios_pj, dtype: float64}
-------> Coluna: qt_coligados
1.0     31
2.0     15
3.0      6
5.0      3
4.0      2
6.0      2
7.0      1
9.0      1
33.0     1
23.0     1
Name: qt_coligados, dtype: int64
{'total': 555, 'percentages': 1.0     49.206349
2.0     23.809524
3.0      9.523810
5.0      4.761905
4.0      3.174603
6.0      3.174603
7.0      1.587302
9.0      1.587302
33.0     1.587302
23.0     1.587302
Name: qt_coligados, dtype: float64}
-------> Coluna: qt_socios_coligados
1.0     25
2.0     16
3.0      9
9.0      3
4.0      2
5.0      2
42.0     1
14.0     1
6.0      1
20.0     1
44.0     1
23.0     1
Name: qt_socios_coligados, dtype: int64
{'total': 555, 'percentages': 1.0     39.682540
2.0     25.396825
3.0     14.285714
9.0      4.761905
4.0      3.174603
5.0      3.174603
42.0     1.587302
14.0     1.587302
6.0      1.587302
20.0     1.587302
44.0     1.587302
23.0     1.587302
Name: qt_socios_coligados, dtype: float64}
-------> Coluna: qt_coligados_matriz
1.0     31
2.0     15
3.0      6
5.0      4
6.0      2
9.0      1
4.0      1
11.0     1
33.0     1
23.0     1
Name: qt_coligados_matriz, dtype: int64
{'total': 555, 'percentages': 1.0     49.206349
2.0     23.809524
3.0      9.523810
5.0      6.349206
6.0      3.174603
9.0      1.587302
4.0      1.587302
11.0     1.587302
33.0     1.587302
23.0     1.587302
Name: qt_coligados_matriz, dtype: float64}
-------> Coluna: qt_coligados_ativo
1.0     30
2.0     15
3.0      6
5.0      3
9.0      2
42.0     1
0.0      1
6.0      1
4.0      1
20.0     1
33.0     1
23.0     1
Name: qt_coligados_ativo, dtype: int64
{'total': 555, 'percentages': 1.0     47.619048
2.0     23.809524
3.0      9.523810
5.0      4.761905
9.0      3.174603
42.0     1.587302
0.0      1.587302
6.0      1.587302
4.0      1.587302
20.0     1.587302
33.0     1.587302
23.0     1.587302
Name: qt_coligados_ativo, dtype: float64}
-------> Coluna: qt_coligados_baixada
0.0    63
Name: qt_coligados_baixada, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_coligados_baixada, dtype: float64}
-------> Coluna: qt_coligados_inapta
0.0    62
1.0     1
Name: qt_coligados_inapta, dtype: int64
{'total': 555, 'percentages': 0.0    98.412698
1.0     1.587302
Name: qt_coligados_inapta, dtype: float64}
-------> Coluna: qt_coligados_suspensa
0.0    63
Name: qt_coligados_suspensa, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_coligados_suspensa, dtype: float64}
-------> Coluna: qt_coligados_nula
0.0    63
Name: qt_coligados_nula, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_coligados_nula, dtype: float64}
-------> Coluna: idade_media_coligadas
27.733333     2
241.333333    1
125.633333    1
244.197980    1
93.733333     1
             ..
206.133333    1
84.433333     1
368.266667    1
106.066667    1
86.500000     1
Name: idade_media_coligadas, Length: 62, dtype: int64
{'total': 555, 'percentages': 27.733333     3.174603
241.333333    1.587302
125.633333    1.587302
244.197980    1.587302
93.733333     1.587302
                ...
206.133333    1.587302
84.433333     1.587302
368.266667    1.587302
106.066667    1.587302
86.500000     1.587302
Name: idade_media_coligadas, Length: 62, dtype: float64}
-------> Coluna: idade_maxima_coligadas
27.733333     2
518.666667    1
27.633333     1
354.533333    1
87.700000     1
             ..
368.266667    1
106.066667    1
54.966667     1
135.433333    1
86.500000     1
Name: idade_maxima_coligadas, Length: 62, dtype: int64
{'total': 555, 'percentages': 27.733333     3.174603
518.666667    1.587302
27.633333     1.587302
354.533333    1.587302
87.700000     1.587302
                ...
368.266667    1.587302
106.066667    1.587302
54.966667     1.587302
135.433333    1.587302
86.500000     1.587302
Name: idade_maxima_coligadas, Length: 62, dtype: float64}
-------> Coluna: idade_minima_coligadas
27.733333     2
10.166667     1
125.633333    1
1.566667      1
93.733333     1
             ..
8.366667      1
147.433333    1
123.833333    1
86.500000     1
33.000000     1
Name: idade_minima_coligadas, Length: 62, dtype: int64
{'total': 555, 'percentages': 27.733333     3.174603
10.166667     1.587302
125.633333    1.587302
1.566667      1.587302
93.733333     1.587302
                ...
8.366667      1.587302
147.433333    1.587302
123.833333    1.587302
86.500000     1.587302
33.000000     1.587302
Name: idade_minima_coligadas, Length: 62, dtype: float64}
-------> Coluna: coligada_mais_nova_ativa
27.733333     2
10.166667     1
125.633333    1
16.233333     1
1.566667      1
             ..
168.566667    1
8.366667      1
147.433333    1
123.833333    1
33.000000     1
Name: coligada_mais_nova_ativa, Length: 61, dtype: int64
{'total': 555, 'percentages': 27.733333     3.225806
10.166667     1.612903
125.633333    1.612903
16.233333     1.612903
1.566667      1.612903
                ...
168.566667    1.612903
8.366667      1.612903
147.433333    1.612903
123.833333    1.612903
33.000000     1.612903
Name: coligada_mais_nova_ativa, Length: 61, dtype: float64}
-------> Coluna: coligada_mais_antiga_ativa
27.733333     2
518.666667    1
10.166667     1
521.800000    1
354.533333    1
             ..
84.433333     1
368.266667    1
106.066667    1
54.966667     1
86.500000     1
Name: coligada_mais_antiga_ativa, Length: 61, dtype: int64
{'total': 555, 'percentages': 27.733333     3.225806
518.666667    1.612903
10.166667     1.612903
521.800000    1.612903
354.533333    1.612903
                ...
84.433333     1.612903
368.266667    1.612903
106.066667    1.612903
54.966667     1.612903
86.500000     1.612903
Name: coligada_mais_antiga_ativa, Length: 61, dtype: float64}
-------> Coluna: idade_media_coligadas_ativas
27.733333     2
241.333333    1
312.100000    1
53.333333     1
244.197980    1
             ..
81.566667     1
206.133333    1
84.433333     1
368.266667    1
86.500000     1
Name: idade_media_coligadas_ativas, Length: 61, dtype: int64
{'total': 555, 'percentages': 27.733333     3.225806
241.333333    1.612903
312.100000    1.612903
53.333333     1.612903
244.197980    1.612903
                ...
81.566667     1.612903
206.133333    1.612903
84.433333     1.612903
368.266667    1.612903
86.500000     1.612903
Name: idade_media_coligadas_ativas, Length: 61, dtype: float64}
-------> Coluna: coligada_mais_nova_baixada
Series([], Name: coligada_mais_nova_baixada, dtype: int64)
{'total': 555, 'percentages': Series([], Name: coligada_mais_nova_baixada, dtype: float64)}
-------> Coluna: coligada_mais_antiga_baixada
Series([], Name: coligada_mais_antiga_baixada, dtype: int64)
{'total': 555, 'percentages': Series([], Name: coligada_mais_antiga_baixada, dtype: float64)}
-------> Coluna: idade_media_coligadas_baixadas
Series([], Name: idade_media_coligadas_baixadas, dtype: int64)
{'total': 555, 'percentages': Series([], Name: idade_media_coligadas_baixadas, dtype: float64)}
-------> Coluna: qt_coligados_sa
0.0     62
13.0     1
Name: qt_coligados_sa, dtype: int64
{'total': 555, 'percentages': 0.0     98.412698
13.0     1.587302
Name: qt_coligados_sa, dtype: float64}
-------> Coluna: qt_coligados_me
0.0    63
Name: qt_coligados_me, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_coligados_me, dtype: float64}
-------> Coluna: qt_coligados_mei
0.0    63
Name: qt_coligados_mei, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_coligados_mei, dtype: float64}
-------> Coluna: qt_coligados_ltda
0.0    62
1.0     1
Name: qt_coligados_ltda, dtype: int64
{'total': 555, 'percentages': 0.0    98.412698
1.0     1.587302
Name: qt_coligados_ltda, dtype: float64}
-------> Coluna: qt_coligados_epp
0.0    63
Name: qt_coligados_epp, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_coligados_epp, dtype: float64}
-------> Coluna: qt_coligados_norte
0.0     40
1.0     10
2.0      8
5.0      2
9.0      1
15.0     1
3.0      1
Name: qt_coligados_norte, dtype: int64
{'total': 555, 'percentages': 0.0     63.492063
1.0     15.873016
2.0     12.698413
5.0      3.174603
9.0      1.587302
15.0     1.587302
3.0      1.587302
Name: qt_coligados_norte, dtype: float64}
-------> Coluna: qt_coligados_sul
0.0    63
Name: qt_coligados_sul, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_coligados_sul, dtype: float64}
-------> Coluna: qt_coligados_nordeste
0.0     23
1.0     20
2.0      9
3.0      4
42.0     1
5.0      1
7.0      1
6.0      1
4.0      1
20.0     1
31.0     1
Name: qt_coligados_nordeste, dtype: int64
{'total': 555, 'percentages': 0.0     36.507937
1.0     31.746032
2.0     14.285714
3.0      6.349206
42.0     1.587302
5.0      1.587302
7.0      1.587302
6.0      1.587302
4.0      1.587302
20.0     1.587302
31.0     1.587302
Name: qt_coligados_nordeste, dtype: float64}
-------> Coluna: qt_coligados_centro
0.0    62
1.0     1
Name: qt_coligados_centro, dtype: int64
{'total': 555, 'percentages': 0.0    98.412698
1.0     1.587302
Name: qt_coligados_centro, dtype: float64}
-------> Coluna: qt_coligados_sudeste
0.0    59
1.0     2
2.0     1
7.0     1
Name: qt_coligados_sudeste, dtype: int64
{'total': 555, 'percentages': 0.0    93.650794
1.0     3.174603
2.0     1.587302
7.0     1.587302
Name: qt_coligados_sudeste, dtype: float64}
-------> Coluna: qt_coligados_exterior
0.0    63
Name: qt_coligados_exterior, dtype: int64
{'total': 555, 'percentages': 0.0    100.0
Name: qt_coligados_exterior, dtype: float64}
-------> Coluna: qt_ufs_coligados
1.0    54
2.0     6
3.0     1
5.0     1
4.0     1
Name: qt_ufs_coligados, dtype: int64
{'total': 555, 'percentages': 1.0    85.714286
2.0     9.523810
3.0     1.587302
5.0     1.587302
4.0     1.587302
Name: qt_ufs_coligados, dtype: float64}
-------> Coluna: qt_regioes_coligados
1.0    59
2.0     3
3.0     1
Name: qt_regioes_coligados, dtype: int64
{'total': 555, 'percentages': 1.0    93.650794
2.0     4.761905
3.0     1.587302
Name: qt_regioes_coligados, dtype: float64}
-------> Coluna: qt_ramos_coligados
1.0     35
2.0     14
3.0      6
4.0      5
8.0      1
28.0     1
5.0      1
Name: qt_ramos_coligados, dtype: int64
{'total': 555, 'percentages': 1.0     55.555556
2.0     22.222222
3.0      9.523810
4.0      7.936508
8.0      1.587302
28.0     1.587302
5.0      1.587302
Name: qt_ramos_coligados, dtype: float64}
-------> Coluna: qt_coligados_industria
0.0     53
1.0      9
14.0     1
Name: qt_coligados_industria, dtype: int64
{'total': 555, 'percentages': 0.0     84.126984
1.0     14.285714
14.0     1.587302
Name: qt_coligados_industria, dtype: float64}
-------> Coluna: qt_coligados_agropecuaria
0.0    62
1.0     1
Name: qt_coligados_agropecuaria, dtype: int64
{'total': 555, 'percentages': 0.0    98.412698
1.0     1.587302
Name: qt_coligados_agropecuaria, dtype: float64}
-------> Coluna: qt_coligados_comercio
1.0     25
0.0     21
2.0      8
5.0      2
3.0      2
42.0     1
4.0      1
9.0      1
20.0     1
22.0     1
Name: qt_coligados_comercio, dtype: int64
{'total': 555, 'percentages': 1.0     39.682540
0.0     33.333333
2.0     12.698413
5.0      3.174603
3.0      3.174603
42.0     1.587302
4.0      1.587302
9.0      1.587302
20.0     1.587302
22.0     1.587302
Name: qt_coligados_comercio, dtype: float64}
-------> Coluna: qt_coligados_serviÃ§o
0.0     33
1.0     20
2.0      7
4.0      1
3.0      1
11.0     1
Name: qt_coligados_serviÃ§o, dtype: int64
{'total': 555, 'percentages': 0.0     52.380952
1.0     31.746032
2.0     11.111111
4.0      1.587302
3.0      1.587302
11.0     1.587302
Name: qt_coligados_serviÃ§o, dtype: float64}
-------> Coluna: qt_coligados_ccivil
0.0    57
1.0     5
5.0     1
Name: qt_coligados_ccivil, dtype: int64
{'total': 555, 'percentages': 0.0    90.476190
1.0     7.936508
5.0     1.587302
Name: qt_coligados_ccivil, dtype: float64}
-------> Coluna: qt_funcionarios_coligados
0.0       9
2.0       6
3.0       5
1.0       3
6.0       2
4.0       2
15.0      2
178.0     1
62.0      1
32.0      1
48.0      1
9.0       1
137.0     1
3874.0    1
68.0      1
40.0      1
61.0      1
7.0       1
13.0      1
11.0      1
5.0       1
53.0      1
1481.0    1
37.0      1
Name: qt_funcionarios_coligados, dtype: int64
{'total': 555, 'percentages': 0.0       19.565217
2.0       13.043478
3.0       10.869565
1.0        6.521739
6.0        4.347826
4.0        4.347826
15.0       4.347826
178.0      2.173913
62.0       2.173913
32.0       2.173913
48.0       2.173913
9.0        2.173913
137.0      2.173913
3874.0     2.173913
68.0       2.173913
40.0       2.173913
61.0       2.173913
7.0        2.173913
13.0       2.173913
11.0       2.173913
5.0        2.173913
53.0       2.173913
1481.0     2.173913
37.0       2.173913
Name: qt_funcionarios_coligados, dtype: float64}
-------> Coluna: qt_funcionarios_coligados_gp
0.0       9
2.0       6
3.0       5
15.0      3
1.0       3
6.0       2
4.0       2
82.0      1
62.0      1
33.0      1
48.0      1
9.0       1
2271.0    1
141.0     1
148.0     1
13.0      1
11.0      1
5.0       1
53.0      1
4098.0    1
1039.0    1
322.0     1
68.0      1
Name: qt_funcionarios_coligados_gp, dtype: int64
{'total': 555, 'percentages': 0.0       19.565217
2.0       13.043478
3.0       10.869565
15.0       6.521739
1.0        6.521739
6.0        4.347826
4.0        4.347826
82.0       2.173913
62.0       2.173913
33.0       2.173913
48.0       2.173913
9.0        2.173913
2271.0     2.173913
141.0      2.173913
148.0      2.173913
13.0       2.173913
11.0       2.173913
5.0        2.173913
53.0       2.173913
4098.0     2.173913
1039.0     2.173913
322.0      2.173913
68.0       2.173913
Name: qt_funcionarios_coligados_gp, dtype: float64}
-------> Coluna: media_funcionarios_coligados_gp
0.000000       9
2.000000       7
3.000000       4
1.000000       4
7.500000       3
178.173913     1
62.000000      1
6.000000       1
1.500000       1
4.000000       1
48.000000      1
9.000000       1
15.666667      1
15.333333      1
68.000000      1
9.250000       1
13.000000      1
5.500000       1
5.000000       1
6.600000       1
1039.000000    1
454.200000     1
17.666667      1
41.000000      1
Name: media_funcionarios_coligados_gp, dtype: int64
{'total': 555, 'percentages': 0.000000       19.565217
2.000000       15.217391
3.000000        8.695652
1.000000        8.695652
7.500000        6.521739
178.173913      2.173913
62.000000       2.173913
6.000000        2.173913
1.500000        2.173913
4.000000        2.173913
48.000000       2.173913
9.000000        2.173913
15.666667       2.173913
15.333333       2.173913
68.000000       2.173913
9.250000        2.173913
13.000000       2.173913
5.500000        2.173913
5.000000        2.173913
6.600000        2.173913
1039.000000     2.173913
454.200000      2.173913
17.666667       2.173913
41.000000       2.173913
Name: media_funcionarios_coligados_gp, dtype: float64}
-------> Coluna: max_funcionarios_coligados_gp
0.0       9
2.0       6
3.0       5
4.0       3
1.0       3
12.0      3
14.0      2
9.0       1
62.0      1
6.0       1
48.0      1
173.0     1
1151.0    1
68.0      1
31.0      1
13.0      1
8.0       1
5.0       1
26.0      1
1307.0    1
1039.0    1
61.0      1
Name: max_funcionarios_coligados_gp, dtype: int64
{'total': 555, 'percentages': 0.0       19.565217
2.0       13.043478
3.0       10.869565
4.0        6.521739
1.0        6.521739
12.0       6.521739
14.0       4.347826
9.0        2.173913
62.0       2.173913
6.0        2.173913
48.0       2.173913
173.0      2.173913
1151.0     2.173913
68.0       2.173913
31.0       2.173913
13.0       2.173913
8.0        2.173913
5.0        2.173913
26.0       2.173913
1307.0     2.173913
1039.0     2.173913
61.0       2.173913
Name: max_funcionarios_coligados_gp, dtype: float64}
-------> Coluna: min_funcionarios_coligados_gp
0.0       15
3.0        7
1.0        7
2.0        5
1039.0     1
7.0        1
5.0        1
13.0       1
8.0        1
68.0       1
21.0       1
9.0        1
48.0       1
4.0        1
6.0        1
62.0       1
Name: min_funcionarios_coligados_gp, dtype: int64
{'total': 555, 'percentages': 0.0       32.608696
3.0       15.217391
1.0       15.217391
2.0       10.869565
1039.0     2.173913
7.0        2.173913
5.0        2.173913
13.0       2.173913
8.0        2.173913
68.0       2.173913
21.0       2.173913
9.0        2.173913
48.0       2.173913
4.0        2.173913
6.0        2.173913
62.0       2.173913
Name: min_funcionarios_coligados_gp, dtype: float64}
-------> Coluna: vl_folha_coligados
1.854576e+05    5
8.242560e+04    3
1.236384e+05    3
6.181920e+04    2
2.472768e+05    2
2.060640e+04    1
3.090960e+05    1
4.203706e+06    1
5.151600e+05    1
5.357664e+05    1
2.905502e+06    1
1.298203e+06    1
2.884896e+05    1
2.328523e+06    1
3.688546e+06    1
9.272880e+05    1
3.235205e+06    1
1.020017e+07    1
2.866144e+08    1
1.116867e+07    1
3.915216e+05    1
2.472768e+06    1
6.181920e+05    1
3.812184e+06    1
4.945536e+05    1
9.631431e+07    1
1.071533e+06    1
Name: vl_folha_coligados, dtype: int64
{'total': 555, 'percentages': 1.854576e+05    13.513514
8.242560e+04     8.108108
1.236384e+05     8.108108
6.181920e+04     5.405405
2.472768e+05     5.405405
2.060640e+04     2.702703
3.090960e+05     2.702703
4.203706e+06     2.702703
5.151600e+05     2.702703
5.357664e+05     2.702703
2.905502e+06     2.702703
1.298203e+06     2.702703
2.884896e+05     2.702703
2.328523e+06     2.702703
3.688546e+06     2.702703
9.272880e+05     2.702703
3.235205e+06     2.702703
1.020017e+07     2.702703
2.866144e+08     2.702703
1.116867e+07     2.702703
3.915216e+05     2.702703
2.472768e+06     2.702703
6.181920e+05     2.702703
3.812184e+06     2.702703
4.945536e+05     2.702703
9.631431e+07     2.702703
1.071533e+06     2.702703
Name: vl_folha_coligados, dtype: float64}
-------> Coluna: media_vl_folha_coligados
1.854576e+05    5
1.236384e+05    3
8.242560e+04    3
2.472768e+05    2
6.181920e+04    2
5.318414e+05    1
3.090960e+05    1
5.269351e+05    1
4.203706e+06    1
2.575800e+05    1
5.357664e+05    1
4.657046e+05    1
2.905502e+06    1
1.442448e+05    1
1.685967e+07    1
1.078402e+06    1
4.636440e+05    1
1.020017e+07    1
1.902129e+05    1
1.957608e+05    1
6.181920e+05    1
3.812184e+06    1
4.945536e+05    1
2.407858e+07    1
2.060640e+04    1
6.491016e+05    1
5.357664e+05    1
Name: media_vl_folha_coligados, dtype: int64
{'total': 555, 'percentages': 1.854576e+05    13.513514
1.236384e+05     8.108108
8.242560e+04     8.108108
2.472768e+05     5.405405
6.181920e+04     5.405405
5.318414e+05     2.702703
3.090960e+05     2.702703
5.269351e+05     2.702703
4.203706e+06     2.702703
2.575800e+05     2.702703
5.357664e+05     2.702703
4.657046e+05     2.702703
2.905502e+06     2.702703
1.442448e+05     2.702703
1.685967e+07     2.702703
1.078402e+06     2.702703
4.636440e+05     2.702703
1.020017e+07     2.702703
1.902129e+05     2.702703
1.957608e+05     2.702703
6.181920e+05     2.702703
3.812184e+06     2.702703
4.945536e+05     2.702703
2.407858e+07     2.702703
2.060640e+04     2.702703
6.491016e+05     2.702703
5.357664e+05     2.702703
Name: media_vl_folha_coligados, dtype: float64}
-------> Coluna: max_vl_folha_coligados
185457.6       5
247276.8       4
82425.6        3
123638.4       3
61819.2        2

{'total': 555, 'percentages': DE R$ 81.000,01 A R$ 360.000,00             55.849057
ATE R$ 81.000,00                            26.981132
DE R$ 360.000,01 A R$ 1.500.000,00          10.943396
DE R$ 1.500.000,01 A R$ 4.800.000,00         3.396226
DE R$ 4.800.000,01 A R$ 10.000.000,00        1.132075
DE R$ 10.000.000,01 A R$ 30.000.000,00       0.943396
DE R$ 30.000.000,01 A R$ 100.000.000,00      0.377358
ACIMA DE 1 BILHAO DE REAIS                   0.188679
DE R$ 300.000.000,01 A R$ 500.000.000,00     0.188679
Name: de_faixa_faturamento_estimado_grupo, dtype: float64}
-------> Coluna: vl_faturamento_estimado_aux
210000.0      289
50000.0       137
185457.6       25
370915.2        8
556372.8        8
61819.2         6
741830.4        5
930000.0        4
1112745.6       3
1669118.4       3
247276.8        3
1298203.2       2
432734.4        2
0.0             2
309096.0        2
927288.0        2
154548.0        2
2410948.8       2
1483660.8       2
123638.4        2
2110000.0       1
2843683.2       1
3029140.8       1
2163672.0       1
1030320.0       1
4760078.5       1
103032.0        1
51516.0         1
1081836.0       1
20194272.0      1
1730937.6       1
566676.0        1
1792756.8       1
3348540.0       1
2349129.5       1
82425.6         1
5872824.0       1
1050926.4       1
2225491.2       1
2936412.0       1
494553.6        1
Name: vl_faturamento_estimado_aux, dtype: int64
{'total': 555, 'percentages': 210000.0      54.528302
50000.0       25.849057
185457.6       4.716981
370915.2       1.509434
556372.8       1.509434
61819.2        1.132075
741830.4       0.943396
930000.0       0.754717
1112745.6      0.566038
1669118.4      0.566038
247276.8       0.566038
1298203.2      0.377358
432734.4       0.377358
0.0            0.377358
309096.0       0.377358
927288.0       0.377358
154548.0       0.377358
2410948.8      0.377358
1483660.8      0.377358
123638.4       0.377358
2110000.0      0.188679
2843683.2      0.188679
3029140.8      0.188679
2163672.0      0.188679
1030320.0      0.188679
4760078.5      0.188679
103032.0       0.188679
51516.0        0.188679
1081836.0      0.188679
20194272.0     0.188679
1730937.6      0.188679
566676.0       0.188679
1792756.8      0.188679
3348540.0      0.188679
2349129.5      0.188679
82425.6        0.188679
5872824.0      0.188679
1050926.4      0.188679
2225491.2      0.188679
2936412.0      0.188679
494553.6       0.188679
Name: vl_faturamento_estimado_aux, dtype: float64}
-------> Coluna: vl_faturamento_estimado_grupo_aux
210000.0      262
50000.0       137
185457.6       23
420000.0       13
370915.2        8
             ...
618192.0        1
2349129.5       1
3348540.0       1
33880856.0      1
14057501.0      1
Name: vl_faturamento_estimado_grupo_aux, Length: 66, dtype: int64
{'total': 555, 'percentages': 210000.0      49.433962
50000.0       25.849057
185457.6       4.339623
420000.0       2.452830
370915.2       1.509434
                ...
618192.0       0.188679
2349129.5      0.188679
3348540.0      0.188679
33880856.0     0.188679
14057501.0     0.188679
Name: vl_faturamento_estimado_grupo_aux, Length: 66, dtype: float64}
-------> Coluna: qt_ex_funcionarios
0.0      40
1.0      25
2.0      12
5.0       8
4.0       7
6.0       5
8.0       4
14.0      4
3.0       4
7.0       4
11.0      3
12.0      2
34.0      2
17.0      2
19.0      2
9.0       2
10.0      2
13.0      2
35.0      1
37.0      1
28.0      1
21.0      1
15.0      1
18.0      1
43.0      1
32.0      1
64.0      1
23.0      1
38.0      1
61.0      1
132.0     1
25.0      1
29.0      1
155.0     1
Name: qt_ex_funcionarios, dtype: int64
{'total': 555, 'percentages': 0.0      27.397260
1.0      17.123288
2.0       8.219178
5.0       5.479452
4.0       4.794521
6.0       3.424658
8.0       2.739726
14.0      2.739726
3.0       2.739726
7.0       2.739726
11.0      2.054795
12.0      1.369863
34.0      1.369863
17.0      1.369863
19.0      1.369863
9.0       1.369863
10.0      1.369863
13.0      1.369863
35.0      0.684932
37.0      0.684932
28.0      0.684932
21.0      0.684932
15.0      0.684932
18.0      0.684932
43.0      0.684932
32.0      0.684932
64.0      0.684932
23.0      0.684932
38.0      0.684932
61.0      0.684932
132.0     0.684932
25.0      0.684932
29.0      0.684932
155.0     0.684932
Name: qt_ex_funcionarios, dtype: float64}
-------> Coluna: qt_funcionarios_grupo
1.0       37
0.0       32
2.0       20
3.0        6
4.0        6
6.0        4
9.0        4
13.0       4
8.0        3
7.0        3
5.0        2
52.0       2
10.0       2
12.0       2
117.0      1
18.0       1
28.0       1
9281.0     1
14.0       1
87.0       1
25.0       1
21.0       1
42.0       1
1504.0     1
100.0      1
49.0       1
70.0       1
74.0       1
24.0       1
11.0       1
217.0      1
39.0       1
191.0      1
Name: qt_funcionarios_grupo, dtype: int64
{'total': 555, 'percentages': 1.0       25.342466
0.0       21.917808
2.0       13.698630
3.0        4.109589
4.0        4.109589
6.0        2.739726
9.0        2.739726
13.0       2.739726
8.0        2.054795
7.0        2.054795
5.0        1.369863
52.0       1.369863
10.0       1.369863
12.0       1.369863
117.0      0.684932
18.0       0.684932
28.0       0.684932
9281.0     0.684932
14.0       0.684932
87.0       0.684932
25.0       0.684932
21.0       0.684932
42.0       0.684932
1504.0     0.684932
100.0      0.684932
49.0       0.684932
70.0       0.684932
74.0       0.684932
24.0       0.684932
11.0       0.684932
217.0      0.684932
39.0       0.684932
191.0      0.684932
Name: qt_funcionarios_grupo, dtype: float64}
-------> Coluna: percent_func_genero_masc
0.00      32
100.00    22
50.00     11
33.33      5
66.67      4
40.00      2
25.00      2
71.43      1
37.50      1
62.50      1
80.00      1
30.00      1
60.00      1
20.00      1
75.00      1
14.29      1
95.24      1
22.22      1
85.71      1
38.89      1
40.38      1
79.49      1
28.57      1
80.77      1
69.23      1
44.44      1
46.15      1
53.85      1
68.75      1
84.29      1
Name: percent_func_genero_masc, dtype: int64
{'total': 555, 'percentages': 0.00      31.683168
100.00    21.782178
50.00     10.891089
33.33      4.950495
66.67      3.960396
40.00      1.980198
25.00      1.980198
71.43      0.990099
37.50      0.990099
62.50      0.990099
80.00      0.990099
30.00      0.990099
60.00      0.990099
20.00      0.990099
75.00      0.990099
14.29      0.990099
95.24      0.990099
22.22      0.990099
85.71      0.990099
38.89      0.990099
40.38      0.990099
79.49      0.990099
28.57      0.990099
80.77      0.990099
69.23      0.990099
44.44      0.990099
46.15      0.990099
53.85      0.990099
68.75      0.990099
84.29      0.990099
Name: percent_func_genero_masc, dtype: float64}
-------> Coluna: percent_func_genero_fem
100.00    32
0.00      22
50.00     11
66.67      5
33.33      4
60.00      2
75.00      2
14.29      1
62.50      1
37.50      1
20.00      1
70.00      1
31.25      1
40.00      1
80.00      1
25.00      1
77.78      1
19.23      1
20.51      1
85.71      1
61.11      1
28.57      1
30.77      1
59.62      1
55.56      1
46.15      1
53.85      1
4.76       1
71.43      1
15.71      1
Name: percent_func_genero_fem, dtype: int64
{'total': 555, 'percentages': 100.00    31.683168
0.00      21.782178
50.00     10.891089
66.67      4.950495
33.33      3.960396
60.00      1.980198
75.00      1.980198
14.29      0.990099
62.50      0.990099
37.50      0.990099
20.00      0.990099
70.00      0.990099
31.25      0.990099
40.00      0.990099
80.00      0.990099
25.00      0.990099
77.78      0.990099
19.23      0.990099
20.51      0.990099
85.71      0.990099
61.11      0.990099
28.57      0.990099
30.77      0.990099
59.62      0.990099
55.56      0.990099
46.15      0.990099
53.85      0.990099
4.76       0.990099
71.43      0.990099
15.71      0.990099
Name: percent_func_genero_fem, dtype: float64}
-------> Coluna: idade_ate_18
1.0    4
Name: idade_ate_18, dtype: int64
{'total': 555, 'percentages': 1.0    100.0
Name: idade_ate_18, dtype: float64}
-------> Coluna: idade_de_19_a_23
1.0    18
2.0     6
4.0     4
7.0     2
5.0     2
6.0     1
Name: idade_de_19_a_23, dtype: int64
{'total': 555, 'percentages': 1.0    54.545455
2.0    18.181818
4.0    12.121212
7.0     6.060606
5.0     6.060606
6.0     3.030303
Name: idade_de_19_a_23, dtype: float64}
-------> Coluna: idade_de_24_a_28
1.0     21
2.0     10
5.0      4
3.0      4
4.0      3
9.0      2
8.0      1
11.0     1
Name: idade_de_24_a_28, dtype: int64
{'total': 555, 'percentages': 1.0     45.652174
2.0     21.739130
5.0      8.695652
3.0      8.695652
4.0      6.521739
9.0      4.347826
8.0      2.173913
11.0     2.173913
Name: idade_de_24_a_28, dtype: float64}
-------> Coluna: idade_de_29_a_33
1.0     22
2.0     10
3.0      4
4.0      2
23.0     1
8.0      1
6.0      1
5.0      1
11.0     1
Name: idade_de_29_a_33, dtype: int64
{'total': 555, 'percentages': 1.0     51.162791
2.0     23.255814
3.0      9.302326
4.0      4.651163
23.0     2.325581
8.0      2.325581
6.0      2.325581
5.0      2.325581
11.0     2.325581
Name: idade_de_29_a_33, dtype: float64}
-------> Coluna: idade_de_34_a_38
1.0     25
2.0      8
3.0      3
5.0      2
12.0     2
4.0      1
6.0      1
Name: idade_de_34_a_38, dtype: int64
{'total': 555, 'percentages': 1.0     59.523810
2.0     19.047619
3.0      7.142857
5.0      4.761905
12.0     4.761905
4.0      2.380952
6.0      2.380952
Name: idade_de_34_a_38, dtype: float64}
-------> Coluna: idade_de_39_a_43
1.0     23
2.0      3
6.0      1
5.0      1
11.0     1
8.0      1
10.0     1
4.0      1
Name: idade_de_39_a_43, dtype: int64
{'total': 555, 'percentages': 1.0     71.875
2.0      9.375
6.0      3.125
5.0      3.125
11.0     3.125
8.0      3.125
10.0     3.125
4.0      3.125
Name: idade_de_39_a_43, dtype: float64}
-------> Coluna: idade_de_44_a_48
1.0    16
2.0     3
5.0     1
3.0     1
Name: idade_de_44_a_48, dtype: int64
{'total': 555, 'percentages': 1.0    76.190476
2.0    14.285714
5.0     4.761905
3.0     4.761905
Name: idade_de_44_a_48, dtype: float64}
-------> Coluna: idade_de_49_a_53
1.0    18
3.0     2
5.0     1
2.0     1
Name: idade_de_49_a_53, dtype: int64
{'total': 555, 'percentages': 1.0    81.818182
3.0     9.090909
5.0     4.545455
2.0     4.545455
Name: idade_de_49_a_53, dtype: float64}
-------> Coluna: idade_de_54_a_58
1.0    10
2.0     4
Name: idade_de_54_a_58, dtype: int64
{'total': 555, 'percentages': 1.0    71.428571
2.0    28.571429
Name: idade_de_54_a_58, dtype: float64}
-------> Coluna: idade_acima_de_58
1.0    13
2.0     1
3.0     1
Name: idade_acima_de_58, dtype: int64
{'total': 555, 'percentages': 1.0    86.666667
2.0     6.666667
3.0     6.666667
Name: idade_acima_de_58, dtype: float64}
-------> Coluna: grau_instrucao_macro_analfabeto
1.0    1
Name: grau_instrucao_macro_analfabeto, dtype: int64
{'total': 555, 'percentages': 1.0    100.0
Name: grau_instrucao_macro_analfabeto, dtype: float64}
-------> Coluna: grau_instrucao_macro_escolaridade_fundamental
1.0     13
3.0      4
2.0      4
4.0      1
14.0     1
25.0     1
13.0     1
Name: grau_instrucao_macro_escolaridade_fundamental, dtype: int64
{'total': 555, 'percentages': 1.0     52.0
3.0     16.0
2.0     16.0
4.0      4.0
14.0     4.0
25.0     4.0
13.0     4.0
Name: grau_instrucao_macro_escolaridade_fundamental, dtype: float64}
-------> Coluna: grau_instrucao_macro_escolaridade_media
1.0     33
3.0      9
2.0      8
6.0      8
4.0      6
5.0      5
9.0      3
11.0     3
13.0     2
7.0      2
70.0     1
24.0     1
38.0     1
10.0     1
12.0     1
14.0     1
18.0     1
Name: grau_instrucao_macro_escolaridade_media, dtype: int64
{'total': 555, 'percentages': 1.0     38.372093
3.0     10.465116
2.0      9.302326
6.0      9.302326
4.0      6.976744
5.0      5.813953
9.0      3.488372
11.0     3.488372
13.0     2.325581
7.0      2.325581
70.0     1.162791
24.0     1.162791
38.0     1.162791
10.0     1.162791
12.0     1.162791
14.0     1.162791
18.0     1.162791
Name: grau_instrucao_macro_escolaridade_media, dtype: float64}
-------> Coluna: grau_instrucao_macro_escolaridade_superior
1.0    17
2.0     4
4.0     1
3.0     1
Name: grau_instrucao_macro_escolaridade_superior, dtype: int64
{'total': 555, 'percentages': 1.0    73.913043
2.0    17.391304
4.0     4.347826
3.0     4.347826
Name: grau_instrucao_macro_escolaridade_superior, dtype: float64}
-------> Coluna: grau_instrucao_macro_desconhecido
Series([], Name: grau_instrucao_macro_desconhecido, dtype: int64)
{'total': 555, 'percentages': Series([], Name: grau_instrucao_macro_desconhecido, dtype: float64)}
-------> Coluna: total
1.0     36
2.0     17
3.0     11
4.0      6
9.0      5
5.0      4
6.0      3
13.0     3
14.0     2
8.0      2
10.0     2
7.0      2
12.0     1
52.0     1
21.0     1
39.0     1
16.0     1
70.0     1
18.0     1
26.0     1
Name: total, dtype: int64
{'total': 555, 'percentages': 1.0     35.643564
2.0     16.831683
3.0     10.891089
4.0      5.940594
9.0      4.950495
5.0      3.960396
6.0      2.970297
13.0     2.970297
14.0     1.980198
8.0      1.980198
10.0     1.980198
7.0      1.980198
12.0     0.990099
52.0     0.990099
21.0     0.990099
39.0     0.990099
16.0     0.990099
70.0     0.990099
18.0     0.990099
26.0     0.990099
Name: total, dtype: float64}
-------> Coluna: meses_ultima_contratacaco
2.933333     6
6.966667     4
21.133333    3
22.133333    3
25.233333    3
            ..
81.066667    1
53.966667    1
43.533333    1
51.633333    1
10.000000    1
Name: meses_ultima_contratacaco, Length: 102, dtype: int64
{'total': 555, 'percentages': 2.933333     4.580153
6.966667     3.053435
21.133333    2.290076
22.133333    2.290076
25.233333    2.290076
               ...
81.066667    0.763359
53.966667    0.763359
43.533333    0.763359
51.633333    0.763359
10.000000    0.763359
Name: meses_ultima_contratacaco, Length: 102, dtype: float64}
-------> Coluna: qt_admitidos_12meses
0.0     89
1.0     17
2.0      7
3.0      6
4.0      4
7.0      2
6.0      2
14.0     1
9.0      1
15.0     1
5.0      1
Name: qt_admitidos_12meses, dtype: int64
{'total': 555, 'percentages': 0.0     67.938931
1.0     12.977099
2.0      5.343511
3.0      4.580153
4.0      3.053435
7.0      1.526718
6.0      1.526718
14.0     0.763359
9.0      0.763359
15.0     0.763359
5.0      0.763359
Name: qt_admitidos_12meses, dtype: float64}
-------> Coluna: qt_desligados_12meses
0.0     88
1.0     25
2.0      5
3.0      3
5.0      2
11.0     2
6.0      2
16.0     1
15.0     1
9.0      1
19.0     1
Name: qt_desligados_12meses, dtype: int64
{'total': 555, 'percentages': 0.0     67.175573
1.0     19.083969
2.0      3.816794
3.0      2.290076
5.0      1.526718
11.0     1.526718
6.0      1.526718
16.0     0.763359
15.0     0.763359
9.0      0.763359
19.0     0.763359
Name: qt_desligados_12meses, dtype: float64}
-------> Coluna: qt_desligados
0.0      25
1.0      24
2.0      13
4.0       8
5.0       7
6.0       6
7.0       4
8.0       4
14.0      3
3.0       3
11.0      3
19.0      2
13.0      2
12.0      2
9.0       2
34.0      2
17.0      2
10.0      2
29.0      2
15.0      1
133.0     1
25.0      1
155.0     1
23.0      1
37.0      1
18.0      1
61.0      1
38.0      1
32.0      1
43.0      1
16.0      1
21.0      1
35.0      1
64.0      1
Name: qt_desligados, dtype: int64
{'total': 555, 'percentages': 0.0      19.083969
1.0      18.320611
2.0       9.923664
4.0       6.106870
5.0       5.343511
6.0       4.580153
7.0       3.053435
8.0       3.053435
14.0      2.290076
3.0       2.290076
11.0      2.290076
19.0      1.526718
13.0      1.526718
12.0      1.526718
9.0       1.526718
34.0      1.526718
17.0      1.526718
10.0      1.526718
29.0      1.526718
15.0      0.763359
133.0     0.763359
25.0      0.763359
155.0     0.763359
23.0      0.763359
37.0      0.763359
18.0      0.763359
61.0      0.763359
38.0      0.763359
32.0      0.763359
43.0      0.763359
16.0      0.763359
21.0      0.763359
35.0      0.763359
64.0      0.763359
Name: qt_desligados, dtype: float64}
-------> Coluna: qt_admitidos
1.0      33
2.0      14
4.0      12
6.0       7
3.0       5
8.0       5
13.0      4
9.0       4
7.0       4
10.0      4
15.0      3
11.0      2
12.0      2
26.0      2
36.0      2
27.0      2
22.0      2
5.0       2
34.0      1
21.0      1
164.0     1
23.0      1
62.0      1
41.0      1
43.0      1
203.0     1
69.0      1
49.0      1
24.0      1
47.0      1
20.0      1
100.0     1
14.0      1
45.0      1
48.0      1
50.0      1
65.0      1
19.0      1
18.0      1
39.0      1
Name: qt_admitidos, dtype: int64
{'total': 555, 'percentages': 1.0      25.190840
2.0      10.687023
4.0       9.160305
6.0       5.343511
3.0       3.816794
8.0       3.816794
13.0      3.053435
9.0       3.053435
7.0       3.053435
10.0      3.053435
15.0      2.290076
11.0      1.526718
12.0      1.526718
26.0      1.526718
36.0      1.526718
27.0      1.526718
22.0      1.526718
5.0       1.526718
34.0      0.763359
21.0      0.763359
164.0     0.763359
23.0      0.763359
62.0      0.763359
41.0      0.763359
43.0      0.763359
203.0     0.763359
69.0      0.763359
49.0      0.763359
24.0      0.763359
47.0      0.763359
20.0      0.763359
100.0     0.763359
14.0      0.763359
45.0      0.763359
48.0      0.763359
50.0      0.763359
65.0      0.763359
19.0      0.763359
18.0      0.763359
39.0      0.763359
Name: qt_admitidos, dtype: float64}
-------> Coluna: media_meses_servicos_all
23.200000    2
9.166667     1
17.895238    1
23.222222    1
23.245977    1
            ..
40.383333    1
19.035772    1
50.600000    1
1.033333     1
38.000000    1
Name: media_meses_servicos_all, Length: 130, dtype: int64
{'total': 555, 'percentages': 23.200000    1.526718
9.166667     0.763359
17.895238    0.763359
23.222222    0.763359
23.245977    0.763359
               ...
40.383333    0.763359
19.035772    0.763359
50.600000    0.763359
1.033333     0.763359
38.000000    0.763359
Name: media_meses_servicos_all, Length: 130, dtype: float64}
-------> Coluna: max_meses_servicos_all
89.200000    4
49.600000    2
43.533333    2
93.266667    2
52.766667    2
            ..
25.233333    1
39.566667    1
88.166667    1
5.800000     1
10.000000    1
Name: max_meses_servicos_all, Length: 119, dtype: int64
{'total': 555, 'percentages': 89.200000    3.053435
49.600000    1.526718
43.533333    1.526718
93.266667    1.526718
52.766667    1.526718
               ...
25.233333    0.763359
39.566667    0.763359
88.166667    0.763359
5.800000     0.763359
10.000000    0.763359
Name: max_meses_servicos_all, Length: 119, dtype: float64}
-------> Coluna: min_meses_servicos_all
1.000000     8
0.000000     5
3.066667     4
2.033333     3
1.033333     3
            ..
15.133333    1
10.133333    1
43.533333    1
3.966667     1
10.100000    1
Name: min_meses_servicos_all, Length: 100, dtype: int64
{'total': 555, 'percentages': 1.000000     6.106870
0.000000     3.816794
3.066667     3.053435
2.033333     2.290076
1.033333     2.290076
               ...
15.133333    0.763359
10.133333    0.763359
43.533333    0.763359
3.966667     0.763359
10.100000    0.763359
Name: min_meses_servicos_all, Length: 100, dtype: float64}
-------> Coluna: media_meses_servicos
49.600000     2
23.200000     2
66.833333     2
23.533333     2
18.133333     2
             ..
25.233333     1
53.103704     1
108.088889    1
28.977778     1
10.000000     1
Name: media_meses_servicos, Length: 96, dtype: int64
{'total': 555, 'percentages': 49.600000     1.980198
23.200000     1.980198
66.833333     1.980198
23.533333     1.980198
18.133333     1.980198
                ...
25.233333     0.990099
53.103704     0.990099
108.088889    0.990099
28.977778     0.990099
10.000000     0.990099
Name: media_meses_servicos, Length: 96, dtype: float64}
-------> Coluna: max_meses_servicos
89.200000    4
21.133333    3
93.266667    2
95.233333    2
25.233333    2
            ..
27.266667    1
13.366667    1
38.366667    1
5.800000     1
10.000000    1

In [52]:
df['fl_matriz'].value_counts()
(df['fl_matriz'].value_counts()/df['fl_matriz'].count())*100
obj = {
    "total": len(df['fl_matriz']),
    "percentages": (df['fl_matriz'].value_counts()/df['fl_matriz'].count())*100
}
obj

{'total': 555,
 'percentages': True     93.513514
 False     6.486486
 Name: fl_matriz, dtype: float64}

In [15]:
df.dtypes

Unnamed: 0                   int64
id                          object
fl_matriz                     bool
de_natureza_juridica        object
sg_uf                       object
                            ...
qt_funcionarios_24meses    float64
tx_crescimento_12meses     float64
tx_crescimento_24meses     float64
tx_rotatividade            float64
qt_filiais                   int64
Length: 182, dtype: object

In [16]:
df.dtypes.value_counts()

float64    142
object      22
bool        14
int64        4
dtype: int64

In [26]:
df['de_saude_rescencia'].value_counts()

ACIMA DE 1 ANO    453
ATE 1 ANO          55
SEM INFORMACAO     36
Name: de_saude_rescencia, dtype: int64